### ISSUE TITLE
[BUG] ! jupyterlab The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by chanyoungP** [brickstudy/infra-docs#9]
## 🧨 주요 상황

mac m1 

spark local 환경에서 사용하기 위해 infra-docs clone 이후 
1. spark 경로 접속
2.docker-compsoe.yaml 파일 확인 후 `docker-compose up -d` 실행
<img width="1037" alt="image" src="https://github.com/brickstudy/infra-docs/assets/67907678/88d193bc-0743-4edc-9708-fa2b4185f649">

host platform과 문제 발생 

이후 local host 8888 접속 불가

이전 Onboarding spark 로컬은 접속 가능합니다.. ㅜㅜ 

<br>

## 🔗 관련 이슈 참고

- 

<br>

## 📌 진행상황

> *오류 요청자가 작업자가 아닐 경우 진행상황 부분은 그대로 두시면 됩니다!!
> *작업 진행자의 경우 아래 진행상황에 예상 마감 일정까지 함께 기재해주세요!!

- [ ] 요건파악(~기간)
  - [ ] 작업진행 일정 공유
- [ ] 작업 진행
- [ ] 요청자 확인

**Comment by seoyeong200** [comment]
### 문제 원인

오류 메세지에서 보이는 것처럼 칩 호환성 문제입니다. 이미지가 개발된 환경은 intel 칩이고(linux/amd64) 문제가 발생한 로컬 환경이 m1칩(linux/amd64/v8)입니다.  cpu 아키텍처가 서로 다른데 기본적으로 도커가 해당 플랫폼에 맞춰서 빌드되기 때문에,호환 문제가 발생했습니다.

### 문제 헤결 방안

저희 공용 hub에 업로드해두었던, spark/docker-compose.yml에서 image로 사용하는 도커 이미지를 multi-architecture 이미지로 재빌드하여 linux/amd64, linux/arm64/v8 두 아케텍처를 지원할 수 있게끔 했고, 허브에 다시 업로드해두었습니다.

### how to solve

1. 기존 Pull 해왔던 이미지를 삭제합니다. `docker rmi brickstudy/jupyter-spark:latest`
2. 컨테이너 인스턴스를 다시 띄웁니다. `docker-compose up -d`
 

@chanyoungP 님, 테스트 한번 부탁드립니다!

**Comment by chanyoungP** [comment]
### 테스트 결과

정상 작동합니다. 

이전에 사용하던 로컬 포트 종료 과정에서 문제가 생겨서 다시 폴더 다시 clone 해서 작동시켰습니다. 

감사합니다 ~
